name: Test PowerShell Module Function

on:
  workflow_dispatch:
    inputs:
      moduleName:
        description: "PowerShell module name"
        required: true
      testName:
        description: "Function name"
        required: true

jobs:
  test:
    name: Run Pester Tests on PowerShell Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import Module
        run: pwsh -Command 'Import-Module ./powershell/modules/${{ github.event.inputs.moduleName }} -Force'

      - name: Run Pester Unit Tests
        run: pwsh -Command 'Invoke-Pester ./powershell/modules/${{ github.event.inputs.moduleName }}/tests/unit/${{ github.event.inputs.testName }}.Tests.ps1 -Output Detailed'
