name: Test PowerShell Module Function

on:
  workflow_dispatch:
    inputs:
      moduleName:
        description: "PowerShell module name"
        required: true
      testName:
        description: "Function name"
        required: true

jobs:
  test:
    name: Run Pester Tests on PowerShell Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Pester Unit Tests
        run: |
          $unitTestFile = './powershell/modules/${{ github.event.inputs.moduleName }}/tests/unit/${{ github.event.inputs.testName }}.Tests.ps1'
          $integrationTestFile = './powershell/modules/${{ github.event.inputs.moduleName }}/tests/integration/${{ github.event.inputs.testName }}.Tests.ps1'

          if($unitTestFile) {
            Invoke-Pester $unitTestFile -Output Detailed
          }

          if($integrationTestFile) {
            Invoke-Pester $integrationTestFile -Output Detailed
          }

        shell: pwsh
